export const BUTTONS_TEXT = {
  Result: "Результат",
  NextQuestion: "Наступне питання",
  Save: "Зберігти",
  Submit: "Відправити",
  Navigate: "Перейти до тестів",
  Reg: "Реєстрація",
  Auth: "Увійти",
  Edit: "Редагувати",
  Delete: "Видалити",
  Details: "Детальніше",
  Next: "Наступна",
  Previous: "Попередня",
  Post: "Всі статті",
  Exit: "Вихід",
  Refresh: "Пройти знову",
  Test: "Пройти тест",
};
